export const fakeOrderList = [
  {
    id: "001",
    shippingFee: "1",

    trackingLink: "https://www.google1.com.vn/",
    orderCode: "Code 001",
    status: "waiting",
    serviceName: "shipping",
    serviceCode: "shipping 001",
    courierName: "GHTK 001",
    sourceId: 1,

    weight: {
      real: 1,
      converted: 1,
      convertedWithMultiplier: 1,
      multiplier: 1,
      sent: 1,
    },
  },
  {
    id: "002",
    shippingFee: "2",

    trackingLink: "https://www.google2.com.vn/",
    orderCode: "Code 002",
    status: "waiting",
    serviceName: "shipping",
    serviceCode: "shipping 002",
    courierName: "GHTK 002",
    sourceId: 2,

    weight: {
      real: 2,
      converted: 2,
      convertedWithMultiplier: 2,
      multiplier: 2,
      sent: 2,
    },
  },
  {
    id: "003",
    shippingFee: "3",

    trackingLink: "https://www.google3.com.vn/",
    orderCode: "Code 003",
    status: "waiting",
    serviceName: "shipping",
    serviceCode: "shipping 003",
    courierName: "GHTK 003",
    sourceId: 3,

    weight: {
      real: 3,
      converted: 3,
      convertedWithMultiplier: 3,
      multiplier: 3,
      sent: 3,
    },
  },
  {
    id: "004",
    shippingFee: "4",

    trackingLink: "https://www.google4.com.vn/",
    orderCode: "Code 004",
    status: "waiting",
    serviceName: "shipping",
    serviceCode: "shipping 004",
    courierName: "GHTK 004",
    sourceId: 4,

    weight: {
      real: 4,
      converted: 4,
      convertedWithMultiplier: 4,
      multiplier: 4,
      sent: 4,
    },
  },
  {
    id: "005",
    shippingFee: "5",

    trackingLink: "https://www.google5.com.vn/",
    orderCode: "Code 005",
    status: "waiting",
    serviceName: "shipping",
    serviceCode: "shipping 005",
    courierName: "GHTK 005",
    sourceId: 5,

    weight: {
      real: 5,
      converted: 5,
      convertedWithMultiplier: 5,
      multiplier: 5,
      sent: 5,
    },
  },
  {
    id: "006",
    shippingFee: "6",

    trackingLink: "https://www.google6.com.vn/",
    orderCode: "Code 006",
    status: "waiting",
    serviceName: "shipping",
    serviceCode: "shipping 006",
    courierName: "GHTK 006",
    sourceId: 6,

    weight: {
      real: 6,
      converted: 6,
      convertedWithMultiplier: 6,
      multiplier: 6,
      sent: 6,
    },
  },
  {
    id: "007",
    shippingFee: "7",

    trackingLink: "https://www.google7.com.vn/",
    orderCode: "Code 007",
    status: "waiting",
    serviceName: "shipping",
    serviceCode: "shipping 007",
    courierName: "GHTK 007",
    sourceId: 7,

    weight: {
      real: 7,
      converted: 7,
      convertedWithMultiplier: 7,
      multiplier: 7,
      sent: 7,
    },
  },
  {
    id: "008",
    shippingFee: "8",

    trackingLink: "https://www.google8.com.vn/",
    orderCode: "Code 008",
    status: "waiting",
    serviceName: "shipping",
    serviceCode: "shipping 008",
    courierName: "GHTK 008",
    sourceId: 8,

    weight: {
      real: 8,
      converted: 8,
      convertedWithMultiplier: 8,
      multiplier: 8,
      sent: 8,
    },
  },
];

export const fakeDetailOrder = [
  {
    id: "001",
    delivery_id: "001",
    warehouse_id: "GHTK 001",
    user_id: "User 001",
    name: "Đơn hàng 001",
    phone: "0905.001",
    address: "001 Da Nang, Viet Nam",
    province_name: "001 Hoa Vang, Da Nang",
    province_code: "001 DNG",
    district_name: "001 Hoa Vang",
    district_code: "001 HVG",
    ward_name: "001 Hoa Xuan",
    ward_code: "001 HXN",
    total_amount: 100000,
    cod_amount: 10000,
    service: "shipping",
    order_code: "001",
    status: "waiting",
    payment_method: "cash",
    note: "none",
    is_preorder: false,
    restock_at: "Da Nang",
    real_ip: "001",
  },
  {
    id: "002",
    delivery_id: "002",
    warehouse_id: "GHTK 002",
    user_id: "User 002",
    name: "Đơn hàng 002",
    phone: "0905.002",
    address: "002 Da Nang, Viet Nam",
    province_name: "002 Hoa Vang, Da Nang",
    province_code: "002 DNG",
    district_name: "002 Hoa Vang",
    district_code: "002 HVG",
    ward_name: "002 Hoa Xuan",
    ward_code: "002 HXN",
    total_amount: 200000,
    cod_amount: 20000,
    service: "shipping",
    order_code: "002",
    status: "waiting",
    payment_method: "cash",
    note: "none",
    is_preorder: false,
    restock_at: "Da Nang",
    real_ip: "002",
  },
  {
    id: "003",
    delivery_id: "003",
    warehouse_id: "GHTK 003",
    user_id: "User 003",
    name: "Đơn hàng 003",
    phone: "0905.003",
    address: "003 Da Nang, Viet Nam",
    province_name: "003 Hoa Vang, Da Nang",
    province_code: "003 DNG",
    district_name: "003 Hoa Vang",
    district_code: "003 HVG",
    ward_name: "003 Hoa Xuan",
    ward_code: "003 HXN",
    total_amount: 300000,
    cod_amount: 30000,
    service: "shipping",
    order_code: "003",
    status: "waiting",
    payment_method: "cash",
    note: "none",
    is_preorder: false,
    restock_at: "Da Nang",
    real_ip: "003",
  },
  {
    id: "004",
    delivery_id: "004",
    warehouse_id: "GHTK 004",
    user_id: "User 004",
    name: "Đơn hàng 004",
    phone: "0905.004",
    address: "004 Da Nang, Viet Nam",
    province_name: "004 Hoa Vang, Da Nang",
    province_code: "004 DNG",
    district_name: "004 Hoa Vang",
    district_code: "004 HVG",
    ward_name: "004 Hoa Xuan",
    ward_code: "004 HXN",
    total_amount: 400000,
    cod_amount: 40000,
    service: "shipping",
    order_code: "004",
    status: "waiting",
    payment_method: "cash",
    note: "none",
    is_preorder: false,
    restock_at: "Da Nang",
    real_ip: "004",
  },
  {
    id: "005",
    delivery_id: "005",
    warehouse_id: "GHTK 005",
    user_id: "User 005",
    name: "Đơn hàng 005",
    phone: "0905.005",
    address: "005 Da Nang, Viet Nam",
    province_name: "005 Hoa Vang, Da Nang",
    province_code: "005 DNG",
    district_name: "005 Hoa Vang",
    district_code: "005 HVG",
    ward_name: "005 Hoa Xuan",
    ward_code: "005 HXN",
    total_amount: 500000,
    cod_amount: 50000,
    service: "shipping",
    order_code: "005",
    status: "waiting",
    payment_method: "cash",
    note: "none",
    is_preorder: false,
    restock_at: "Da Nang",
    real_ip: "005",
  },
  {
    id: "006",
    delivery_id: "006",
    warehouse_id: "GHTK 006",
    user_id: "User 006",
    name: "Đơn hàng 006",
    phone: "0905.006",
    address: "006 Da Nang, Viet Nam",
    province_name: "006 Hoa Vang, Da Nang",
    province_code: "006 DNG",
    district_name: "006 Hoa Vang",
    district_code: "006 HVG",
    ward_name: "006 Hoa Xuan",
    ward_code: "006 HXN",
    total_amount: 600000,
    cod_amount: 60000,
    service: "shipping",
    order_code: "006",
    status: "waiting",
    payment_method: "cash",
    note: "none",
    is_preorder: false,
    restock_at: "Da Nang",
    real_ip: "006",
  },
  {
    id: "007",
    delivery_id: "007",
    warehouse_id: "GHTK 007",
    user_id: "User 007",
    name: "Đơn hàng 007",
    phone: "0905.007",
    address: "007 Da Nang, Viet Nam",
    province_name: "007 Hoa Vang, Da Nang",
    province_code: "007 DNG",
    district_name: "007 Hoa Vang",
    district_code: "007 HVG",
    ward_name: "007 Hoa Xuan",
    ward_code: "007 HXN",
    total_amount: 700000,
    cod_amount: 70000,
    service: "shipping",
    order_code: "007",
    status: "waiting",
    payment_method: "cash",
    note: "none",
    is_preorder: false,
    restock_at: "Da Nang",
    real_ip: "007",
  },
  {
    id: "008",
    delivery_id: "008",
    warehouse_id: "GHTK 008",
    user_id: "User 008",
    name: "Đơn hàng 008",
    phone: "0905.008",
    address: "008 Da Nang, Viet Nam",
    province_name: "008 Hoa Vang, Da Nang",
    province_code: "008 DNG",
    district_name: "008 Hoa Vang",
    district_code: "008 HVG",
    ward_name: "008 Hoa Xuan",
    ward_code: "008 HXN",
    total_amount: 800000,
    cod_amount: 80000,
    service: "shipping",
    order_code: "008",
    status: "waiting",
    payment_method: "cash",
    note: "none",
    is_preorder: false,
    restock_at: "Da Nang",
    real_ip: "008",
  },
];

export const fakeDeliveryList = [
  {
    code: "GHN",
    slug: "ghn",
    name: "Giao hàng nhanh",
    deactive: true,
    created_at: "2022-05-09T10:20:52.552837858Z",
    updated_at: "2022-05-09T10:20:52.552837858Z",
  },
  {
    code: "GHTK",
    slug: "ghtk",
    name: "Giao hàng tiết kiệm",
    deactive: false,
    created_at: "2022-05-09T10:20:52.552837858Z",
    updated_at: "2022-05-09T10:20:52.552837858Z",
  },
  {
    code: "VTP",
    slug: "vtp",
    name: "Viettel Post",
    deactive: true,
    created_at: "2022-05-09T10:20:52.552837858Z",
    updated_at: "2022-05-09T10:20:52.552837858Z",
  },
  {
    code: "SE",
    slug: "se",
    name: "Selly Express",
    deactive: false,
    created_at: "2022-05-09T10:20:52.552837858Z",
    updated_at: "2022-05-09T10:20:52.552837858Z",
  },
];

export const fakeStaffList = {
  vinh: {
    avatar: {
      dimensions: {
        md: {
          height: 250,
          url: "https://media.selly.vn/unibag-develop/md_default_avatar.png",
          width: 750,
        },
        sm: {
          height: 130,
          url: "https://media.selly.vn/unibag-develop/sm_default_avatar.png",
          width: 375,
        },
      },
      name: "default_avatar.png",
      _id: "5fd62f4b93e7b3ea23387f25",
    },
    isRoot: true,
    name: "Vinh",
    notAllowedLoginAdmin: false,
    permissions: [
      "product_view",
      "transaction_admin",
      "user_view",
      "banner_view",
    ],
    phone: "+84773374284",
    token: "",
    _id: "5fd62f4b93e7b3ea23387f26",
  },
  messi: {
    avatar: {
      dimensions: {
        md: {
          height: 250,
          url: "https://media.selly.vn/unibag-develop/md_default_avatar.png",
          width: 750,
        },
        sm: {
          height: 130,
          url: "https://media.selly.vn/unibag-develop/sm_default_avatar.png",
          width: 375,
        },
      },
      name: "default_avatar.png",
      _id: "5fd62f4b93e7b3ea23387f25",
    },
    isRoot: true,
    name: "Messi",
    notAllowedLoginAdmin: false,
    permissions: [
      "product_view",
      "transaction_admin",
      "user_view",
      "banner_view",
    ],
    phone: "+24061987",
    token: "",
    _id: "5fd62f4b93e7b3ea23387f26",
  },
  other: {
    avatar: {
      dimensions: {
        md: {
          height: 250,
          url: "https://media.selly.vn/unibag-develop/md_default_avatar.png",
          width: 750,
        },
        sm: {
          height: 130,
          url: "https://media.selly.vn/unibag-develop/sm_default_avatar.png",
          width: 375,
        },
      },
      name: "default_avatar.png",
      _id: "5fd62f4b93e7b3ea23387f25",
    },
    isRoot: true,
    name: "Người lạ",
    notAllowedLoginAdmin: false,
    permissions: [
      "product_view",
      "transaction_admin",
      "user_view",
      "banner_view",
    ],
    phone: "113",
    token: "",
    _id: "5fd62f4b93e7b3ea23387f26",
  },
};
